kind: pipeline
type: docker
name: default
workspace:
  path: /workspace

steps:
- name: build_image
  image: docker
  volumes:
  - name : build_docker
    path: /var/run/docker.sock
  commands :
    - docker build docker/ -t rust_docker

- name: doc
  image: rust
  volumes:
  - name: workspace_volume
    path: /workspace
  commands:
  - cargo doc
  detach: true

- name: build
  image: rust_docker
  volumes:
    - name: workspace_volume
      path: /workspace
  pull : never
  commands:
  - cargo build

volumes:
  - name: build_docker
    host:
      path: /var/run/docker.sock
  - name: workspace_volume
    host:
      path: /home/okou/docker-runner/workspace