kind: pipeline
type: docker
name: default


steps:
- name: build_image
  image: docker
  volumes:
  - name : build_docker
    path: /var/run/docker.sock
  commands :
    - docker build docker/ -t rust_docker

- name: doc
  image: rust
  volumes:
  - name : cache
    path : /workspace/build
  commands:
  - export CARGO_TARGET_DIR=/workspace/build
  - cargo doc
  detach: true

- name: build
  image: rust_docker
  pull : never
  volumes:
  - name : cache
    path : /workspace/build
  commands:
  - export CARGO_TARGET_DIR=/workspace/build
  - cargo build

- name: discord notification
  image: appleboy/drone-discord
  settings:
    webhook_id: 
      from_secret: discord_webhook_id
    webhook_token: 
      from_secret: discord_webhook_token
    tts: true
    message: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job.
      {{else}}
        build {{build.number}} failed. Fix me please.
      {{/success}}

volumes:
  - name: build_docker
    host:
      path: /var/run/docker.sock
  - name: cache
    host:
      path: /tmp/drone/sandbox_rs